#!/usr/bin/env node
/**
 * Regenerate fonts/ from Google Fonts.
 *
 * The page self-hosts its fonts so no visitor IP is sent to Google — see
 * fonts/README.md for why. This script is how that directory is rebuilt when
 * the family list changes; it is not run at build or serve time.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Two details that are easy to get wrong by hand:
 *   - Google serves woff2 only to a modern browser user-agent. Fetch with
 *     curl's default UA and you get legacy truetype, several times the size.
 *   - The stylesheet is split into @font-face blocks per unicode-range subset,
 *     each preceded by a /* subset *\/ comment. Only latin and latin-ext are
 *     kept; the rest fall back to system fonts.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'fonts');

// Must match the families the page actually uses (src/00-head.html).
const FAMILIES = [
  'Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400',
  'DM+Mono:ital,wght@0,300;0,400;0,500;1,300',
  'Chakra+Petch:wght@300;400;500;600',
  'Fraunces:ital,opsz,wght@1,9..144,500',
  'Spectral:ital,wght@0,500',
];
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const HEADER = `/* Self-hosted web fonts.
 *
 * These were loaded from fonts.googleapis.com / fonts.gstatic.com, which sends
 * every visitor's IP address to Google. A Munich court (LG München I, Jan 2022)
 * held that doing so without consent breaches the GDPR, and the site has
 * European users. Self-hosting removes the third-party request entirely — no
 * consent banner needed, and the app now renders correctly offline instead of
 * relying on the service worker having cached a Google response.
 *
 * All five families are licensed under the SIL Open Font License 1.1, which
 * permits redistribution. See fonts/OFL.txt.
 *
 * Only the latin and latin-ext subsets are included; the cyrillic, greek, thai
 * and vietnamese subsets Google also serves are dropped to keep the download
 * small. Text in those scripts falls back to a system font, which is the normal
 * behaviour for an unsupported glyph.
 *
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 */
`;

const url = 'https://fonts.googleapis.com/css2?' +
  FAMILIES.map((f) => 'family=' + f).join('&') + '&display=swap';

const res = await fetch(url, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error('Google Fonts CSS fetch failed: ' + res.status);
const css = await res.text();

const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (!blocks.length) throw new Error('no @font-face blocks parsed — did the CSS format change?');

fs.mkdirSync(OUT, { recursive: true });
const faces = [];
let kept = 0, bytes = 0;

for (const [, subset, face] of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;
  const m = face.match(/src:\s*url\((https:[^)]+\.woff2)\)/);
  if (!m) { console.warn('skipping block with no woff2 (subset ' + subset + ')'); continue; }

  const fam = (face.match(/font-family:\s*'([^']+)'/) || [])[1].replace(/\s+/g, '');
  const wt  = (face.match(/font-weight:\s*([^;]+)/)  || [])[1].trim().replace(/\s+/g, '-');
  const st  = (face.match(/font-style:\s*([^;]+)/)   || [])[1].trim();
  const name = [fam, wt, st, subset].join('-').toLowerCase() + '.woff2';

  const r = await fetch(m[1]);
  if (!r.ok) { console.warn('failed to fetch ' + name + ': ' + r.status); continue; }
  const buf = Buffer.from(await r.arrayBuffer());
  fs.writeFileSync(path.join(OUT, name), buf);

  faces.push('/* ' + subset + ' */\n' + face.replace(m[1], '/fonts/' + name));
  kept++; bytes += buf.length;
}

fs.writeFileSync(path.join(OUT, 'fonts.css'), HEADER + '\n' + faces.join('\n\n') + '\n');
console.log('wrote ' + kept + ' font files (' + (bytes / 1024).toFixed(0) + ' KB) and fonts.css');
